package com.topwise.premierpay.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.topwise.premierpay.daoutils.entity.DupTransdata;
import com.topwise.premierpay.daoutils.entity.Operator;
import com.topwise.premierpay.daoutils.entity.ScriptTransdata;
import com.topwise.premierpay.daoutils.entity.TotaTransdata;
import com.topwise.premierpay.trans.model.TestParam;
import com.topwise.premierpay.trans.model.TransData;
import com.topwise.premierpay.trans.model.TransStatusSum;

import com.topwise.premierpay.dao.DupTransdataDao;
import com.topwise.premierpay.dao.OperatorDao;
import com.topwise.premierpay.dao.ScriptTransdataDao;
import com.topwise.premierpay.dao.TotaTransdataDao;
import com.topwise.premierpay.dao.TestParamDao;
import com.topwise.premierpay.dao.TransDataDao;
import com.topwise.premierpay.dao.TransStatusSumDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dupTransdataDaoConfig;
    private final DaoConfig operatorDaoConfig;
    private final DaoConfig scriptTransdataDaoConfig;
    private final DaoConfig totaTransdataDaoConfig;
    private final DaoConfig testParamDaoConfig;
    private final DaoConfig transDataDaoConfig;
    private final DaoConfig transStatusSumDaoConfig;

    private final DupTransdataDao dupTransdataDao;
    private final OperatorDao operatorDao;
    private final ScriptTransdataDao scriptTransdataDao;
    private final TotaTransdataDao totaTransdataDao;
    private final TestParamDao testParamDao;
    private final TransDataDao transDataDao;
    private final TransStatusSumDao transStatusSumDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dupTransdataDaoConfig = daoConfigMap.get(DupTransdataDao.class).clone();
        dupTransdataDaoConfig.initIdentityScope(type);

        operatorDaoConfig = daoConfigMap.get(OperatorDao.class).clone();
        operatorDaoConfig.initIdentityScope(type);

        scriptTransdataDaoConfig = daoConfigMap.get(ScriptTransdataDao.class).clone();
        scriptTransdataDaoConfig.initIdentityScope(type);

        totaTransdataDaoConfig = daoConfigMap.get(TotaTransdataDao.class).clone();
        totaTransdataDaoConfig.initIdentityScope(type);

        testParamDaoConfig = daoConfigMap.get(TestParamDao.class).clone();
        testParamDaoConfig.initIdentityScope(type);

        transDataDaoConfig = daoConfigMap.get(TransDataDao.class).clone();
        transDataDaoConfig.initIdentityScope(type);

        transStatusSumDaoConfig = daoConfigMap.get(TransStatusSumDao.class).clone();
        transStatusSumDaoConfig.initIdentityScope(type);

        dupTransdataDao = new DupTransdataDao(dupTransdataDaoConfig, this);
        operatorDao = new OperatorDao(operatorDaoConfig, this);
        scriptTransdataDao = new ScriptTransdataDao(scriptTransdataDaoConfig, this);
        totaTransdataDao = new TotaTransdataDao(totaTransdataDaoConfig, this);
        testParamDao = new TestParamDao(testParamDaoConfig, this);
        transDataDao = new TransDataDao(transDataDaoConfig, this);
        transStatusSumDao = new TransStatusSumDao(transStatusSumDaoConfig, this);

        registerDao(DupTransdata.class, dupTransdataDao);
        registerDao(Operator.class, operatorDao);
        registerDao(ScriptTransdata.class, scriptTransdataDao);
        registerDao(TotaTransdata.class, totaTransdataDao);
        registerDao(TestParam.class, testParamDao);
        registerDao(TransData.class, transDataDao);
        registerDao(TransStatusSum.class, transStatusSumDao);
    }
    
    public void clear() {
        dupTransdataDaoConfig.clearIdentityScope();
        operatorDaoConfig.clearIdentityScope();
        scriptTransdataDaoConfig.clearIdentityScope();
        totaTransdataDaoConfig.clearIdentityScope();
        testParamDaoConfig.clearIdentityScope();
        transDataDaoConfig.clearIdentityScope();
        transStatusSumDaoConfig.clearIdentityScope();
    }

    public DupTransdataDao getDupTransdataDao() {
        return dupTransdataDao;
    }

    public OperatorDao getOperatorDao() {
        return operatorDao;
    }

    public ScriptTransdataDao getScriptTransdataDao() {
        return scriptTransdataDao;
    }

    public TotaTransdataDao getTotaTransdataDao() {
        return totaTransdataDao;
    }

    public TestParamDao getTestParamDao() {
        return testParamDao;
    }

    public TransDataDao getTransDataDao() {
        return transDataDao;
    }

    public TransStatusSumDao getTransStatusSumDao() {
        return transStatusSumDao;
    }

}
