package com.topwise.premierpay.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.topwise.premierpay.daoutils.entity.DupTransdata;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DUP_TRANSDATA".
*/
public class DupTransdataDao extends AbstractDao<DupTransdata, Long> {

    public static final String TABLENAME = "DUP_TRANSDATA";

    /**
     * Properties of entity DupTransdata.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderNo = new Property(1, String.class, "orderNo", false, "ORDER_NO");
        public final static Property OrderNodis = new Property(2, String.class, "orderNodis", false, "ORDER_NODIS");
        public final static Property Amount = new Property(3, String.class, "amount", false, "AMOUNT");
        public final static Property TipAmount = new Property(4, String.class, "tipAmount", false, "TIP_AMOUNT");
        public final static Property Balance = new Property(5, String.class, "balance", false, "BALANCE");
        public final static Property BalanceFlag = new Property(6, String.class, "balanceFlag", false, "BALANCE_FLAG");
        public final static Property TransNo = new Property(7, long.class, "transNo", false, "TRANS_NO");
        public final static Property OrigTransNo = new Property(8, long.class, "origTransNo", false, "ORIG_TRANS_NO");
        public final static Property BatchNo = new Property(9, long.class, "batchNo", false, "BATCH_NO");
        public final static Property TransType = new Property(10, String.class, "transType", false, "TRANS_TYPE");
        public final static Property MerchID = new Property(11, String.class, "merchID", false, "MERCH_ID");
        public final static Property OrigProcCode = new Property(12, String.class, "origProcCode", false, "ORIG_PROC_CODE");
        public final static Property QrCode = new Property(13, String.class, "qrCode", false, "QR_CODE");
        public final static Property OrigQrCode = new Property(14, String.class, "origQrCode", false, "ORIG_QR_CODE");
        public final static Property QrVoucher = new Property(15, String.class, "qrVoucher", false, "QR_VOUCHER");
        public final static Property OrigQrVoucher = new Property(16, String.class, "origQrVoucher", false, "ORIG_QR_VOUCHER");
        public final static Property TransState = new Property(17, String.class, "transState", false, "TRANS_STATE");
        public final static Property Oper = new Property(18, String.class, "oper", false, "OPER");
        public final static Property Track1 = new Property(19, String.class, "track1", false, "TRACK1");
        public final static Property Track2 = new Property(20, String.class, "track2", false, "TRACK2");
        public final static Property Track3 = new Property(21, String.class, "track3", false, "TRACK3");
        public final static Property IsEncTrack = new Property(22, boolean.class, "isEncTrack", false, "IS_ENC_TRACK");
        public final static Property Reason = new Property(23, String.class, "reason", false, "REASON");
        public final static Property Reserved = new Property(24, String.class, "reserved", false, "RESERVED");
        public final static Property Datetime = new Property(25, String.class, "datetime", false, "DATETIME");
        public final static Property Time = new Property(26, String.class, "time", false, "TIME");
        public final static Property Date = new Property(27, String.class, "date", false, "DATE");
        public final static Property TermID = new Property(28, String.class, "termID", false, "TERM_ID");
        public final static Property Pan = new Property(29, String.class, "pan", false, "PAN");
        public final static Property ExpDate = new Property(30, String.class, "expDate", false, "EXP_DATE");
        public final static Property CardSerialNo = new Property(31, String.class, "cardSerialNo", false, "CARD_SERIAL_NO");
        public final static Property EnterMode = new Property(32, int.class, "enterMode", false, "ENTER_MODE");
        public final static Property HasPin = new Property(33, boolean.class, "hasPin", false, "HAS_PIN");
        public final static Property SendIccData = new Property(34, String.class, "sendIccData", false, "SEND_ICC_DATA");
        public final static Property DupIccData = new Property(35, String.class, "dupIccData", false, "DUP_ICC_DATA");
        public final static Property OrigDate = new Property(36, String.class, "origDate", false, "ORIG_DATE");
        public final static Property ICPositiveData = new Property(37, String.class, "ICPositiveData", false, "ICPOSITIVE_DATA");
        public final static Property Tag9F5B = new Property(38, String.class, "tag9F5B", false, "TAG9_F5_B");
        public final static Property ResponseCode = new Property(39, String.class, "responseCode", false, "RESPONSE_CODE");
        public final static Property ResponseMsg = new Property(40, String.class, "responseMsg", false, "RESPONSE_MSG");
        public final static Property SettleDate = new Property(41, String.class, "settleDate", false, "SETTLE_DATE");
        public final static Property AcqCenterCode = new Property(42, String.class, "acqCenterCode", false, "ACQ_CENTER_CODE");
        public final static Property RefNo = new Property(43, String.class, "refNo", false, "REF_NO");
        public final static Property OrigRefNo = new Property(44, String.class, "origRefNo", false, "ORIG_REF_NO");
        public final static Property AuthCode = new Property(45, String.class, "authCode", false, "AUTH_CODE");
        public final static Property OrigAuthCode = new Property(46, String.class, "origAuthCode", false, "ORIG_AUTH_CODE");
        public final static Property Tc = new Property(47, String.class, "tc", false, "TC");
        public final static Property Arqc = new Property(48, String.class, "arqc", false, "ARQC");
        public final static Property Arpc = new Property(49, String.class, "arpc", false, "ARPC");
        public final static Property Tvr = new Property(50, String.class, "tvr", false, "TVR");
        public final static Property Aid = new Property(51, String.class, "aid", false, "AID");
        public final static Property EmvAppLabel = new Property(52, String.class, "emvAppLabel", false, "EMV_APP_LABEL");
        public final static Property EmvAppName = new Property(53, String.class, "emvAppName", false, "EMV_APP_NAME");
        public final static Property Tsi = new Property(54, String.class, "tsi", false, "TSI");
        public final static Property Atc = new Property(55, String.class, "atc", false, "ATC");
        public final static Property Field22 = new Property(56, String.class, "field22", false, "FIELD22");
        public final static Property Field62 = new Property(57, String.class, "field62", false, "FIELD62");
    }


    public DupTransdataDao(DaoConfig config) {
        super(config);
    }
    
    public DupTransdataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DUP_TRANSDATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ORDER_NO\" TEXT," + // 1: orderNo
                "\"ORDER_NODIS\" TEXT," + // 2: orderNodis
                "\"AMOUNT\" TEXT," + // 3: amount
                "\"TIP_AMOUNT\" TEXT," + // 4: tipAmount
                "\"BALANCE\" TEXT," + // 5: balance
                "\"BALANCE_FLAG\" TEXT," + // 6: balanceFlag
                "\"TRANS_NO\" INTEGER NOT NULL ," + // 7: transNo
                "\"ORIG_TRANS_NO\" INTEGER NOT NULL ," + // 8: origTransNo
                "\"BATCH_NO\" INTEGER NOT NULL ," + // 9: batchNo
                "\"TRANS_TYPE\" TEXT," + // 10: transType
                "\"MERCH_ID\" TEXT," + // 11: merchID
                "\"ORIG_PROC_CODE\" TEXT," + // 12: origProcCode
                "\"QR_CODE\" TEXT," + // 13: qrCode
                "\"ORIG_QR_CODE\" TEXT," + // 14: origQrCode
                "\"QR_VOUCHER\" TEXT," + // 15: qrVoucher
                "\"ORIG_QR_VOUCHER\" TEXT," + // 16: origQrVoucher
                "\"TRANS_STATE\" TEXT," + // 17: transState
                "\"OPER\" TEXT," + // 18: oper
                "\"TRACK1\" TEXT," + // 19: track1
                "\"TRACK2\" TEXT," + // 20: track2
                "\"TRACK3\" TEXT," + // 21: track3
                "\"IS_ENC_TRACK\" INTEGER NOT NULL ," + // 22: isEncTrack
                "\"REASON\" TEXT," + // 23: reason
                "\"RESERVED\" TEXT," + // 24: reserved
                "\"DATETIME\" TEXT," + // 25: datetime
                "\"TIME\" TEXT," + // 26: time
                "\"DATE\" TEXT," + // 27: date
                "\"TERM_ID\" TEXT," + // 28: termID
                "\"PAN\" TEXT," + // 29: pan
                "\"EXP_DATE\" TEXT," + // 30: expDate
                "\"CARD_SERIAL_NO\" TEXT," + // 31: cardSerialNo
                "\"ENTER_MODE\" INTEGER NOT NULL ," + // 32: enterMode
                "\"HAS_PIN\" INTEGER NOT NULL ," + // 33: hasPin
                "\"SEND_ICC_DATA\" TEXT," + // 34: sendIccData
                "\"DUP_ICC_DATA\" TEXT," + // 35: dupIccData
                "\"ORIG_DATE\" TEXT," + // 36: origDate
                "\"ICPOSITIVE_DATA\" TEXT," + // 37: ICPositiveData
                "\"TAG9_F5_B\" TEXT," + // 38: tag9F5B
                "\"RESPONSE_CODE\" TEXT," + // 39: responseCode
                "\"RESPONSE_MSG\" TEXT," + // 40: responseMsg
                "\"SETTLE_DATE\" TEXT," + // 41: settleDate
                "\"ACQ_CENTER_CODE\" TEXT," + // 42: acqCenterCode
                "\"REF_NO\" TEXT," + // 43: refNo
                "\"ORIG_REF_NO\" TEXT," + // 44: origRefNo
                "\"AUTH_CODE\" TEXT," + // 45: authCode
                "\"ORIG_AUTH_CODE\" TEXT," + // 46: origAuthCode
                "\"TC\" TEXT," + // 47: tc
                "\"ARQC\" TEXT," + // 48: arqc
                "\"ARPC\" TEXT," + // 49: arpc
                "\"TVR\" TEXT," + // 50: tvr
                "\"AID\" TEXT," + // 51: aid
                "\"EMV_APP_LABEL\" TEXT," + // 52: emvAppLabel
                "\"EMV_APP_NAME\" TEXT," + // 53: emvAppName
                "\"TSI\" TEXT," + // 54: tsi
                "\"ATC\" TEXT," + // 55: atc
                "\"FIELD22\" TEXT," + // 56: field22
                "\"FIELD62\" TEXT);"); // 57: field62
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DUP_TRANSDATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DupTransdata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(2, orderNo);
        }
 
        String orderNodis = entity.getOrderNodis();
        if (orderNodis != null) {
            stmt.bindString(3, orderNodis);
        }
 
        String amount = entity.getAmount();
        if (amount != null) {
            stmt.bindString(4, amount);
        }
 
        String tipAmount = entity.getTipAmount();
        if (tipAmount != null) {
            stmt.bindString(5, tipAmount);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(6, balance);
        }
 
        String balanceFlag = entity.getBalanceFlag();
        if (balanceFlag != null) {
            stmt.bindString(7, balanceFlag);
        }
        stmt.bindLong(8, entity.getTransNo());
        stmt.bindLong(9, entity.getOrigTransNo());
        stmt.bindLong(10, entity.getBatchNo());
 
        String transType = entity.getTransType();
        if (transType != null) {
            stmt.bindString(11, transType);
        }
 
        String merchID = entity.getMerchID();
        if (merchID != null) {
            stmt.bindString(12, merchID);
        }
 
        String origProcCode = entity.getOrigProcCode();
        if (origProcCode != null) {
            stmt.bindString(13, origProcCode);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(14, qrCode);
        }
 
        String origQrCode = entity.getOrigQrCode();
        if (origQrCode != null) {
            stmt.bindString(15, origQrCode);
        }
 
        String qrVoucher = entity.getQrVoucher();
        if (qrVoucher != null) {
            stmt.bindString(16, qrVoucher);
        }
 
        String origQrVoucher = entity.getOrigQrVoucher();
        if (origQrVoucher != null) {
            stmt.bindString(17, origQrVoucher);
        }
 
        String transState = entity.getTransState();
        if (transState != null) {
            stmt.bindString(18, transState);
        }
 
        String oper = entity.getOper();
        if (oper != null) {
            stmt.bindString(19, oper);
        }
 
        String track1 = entity.getTrack1();
        if (track1 != null) {
            stmt.bindString(20, track1);
        }
 
        String track2 = entity.getTrack2();
        if (track2 != null) {
            stmt.bindString(21, track2);
        }
 
        String track3 = entity.getTrack3();
        if (track3 != null) {
            stmt.bindString(22, track3);
        }
        stmt.bindLong(23, entity.getIsEncTrack() ? 1L: 0L);
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(24, reason);
        }
 
        String reserved = entity.getReserved();
        if (reserved != null) {
            stmt.bindString(25, reserved);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(26, datetime);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(27, time);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(28, date);
        }
 
        String termID = entity.getTermID();
        if (termID != null) {
            stmt.bindString(29, termID);
        }
 
        String pan = entity.getPan();
        if (pan != null) {
            stmt.bindString(30, pan);
        }
 
        String expDate = entity.getExpDate();
        if (expDate != null) {
            stmt.bindString(31, expDate);
        }
 
        String cardSerialNo = entity.getCardSerialNo();
        if (cardSerialNo != null) {
            stmt.bindString(32, cardSerialNo);
        }
        stmt.bindLong(33, entity.getEnterMode());
        stmt.bindLong(34, entity.getHasPin() ? 1L: 0L);
 
        String sendIccData = entity.getSendIccData();
        if (sendIccData != null) {
            stmt.bindString(35, sendIccData);
        }
 
        String dupIccData = entity.getDupIccData();
        if (dupIccData != null) {
            stmt.bindString(36, dupIccData);
        }
 
        String origDate = entity.getOrigDate();
        if (origDate != null) {
            stmt.bindString(37, origDate);
        }
 
        String ICPositiveData = entity.getICPositiveData();
        if (ICPositiveData != null) {
            stmt.bindString(38, ICPositiveData);
        }
 
        String tag9F5B = entity.getTag9F5B();
        if (tag9F5B != null) {
            stmt.bindString(39, tag9F5B);
        }
 
        String responseCode = entity.getResponseCode();
        if (responseCode != null) {
            stmt.bindString(40, responseCode);
        }
 
        String responseMsg = entity.getResponseMsg();
        if (responseMsg != null) {
            stmt.bindString(41, responseMsg);
        }
 
        String settleDate = entity.getSettleDate();
        if (settleDate != null) {
            stmt.bindString(42, settleDate);
        }
 
        String acqCenterCode = entity.getAcqCenterCode();
        if (acqCenterCode != null) {
            stmt.bindString(43, acqCenterCode);
        }
 
        String refNo = entity.getRefNo();
        if (refNo != null) {
            stmt.bindString(44, refNo);
        }
 
        String origRefNo = entity.getOrigRefNo();
        if (origRefNo != null) {
            stmt.bindString(45, origRefNo);
        }
 
        String authCode = entity.getAuthCode();
        if (authCode != null) {
            stmt.bindString(46, authCode);
        }
 
        String origAuthCode = entity.getOrigAuthCode();
        if (origAuthCode != null) {
            stmt.bindString(47, origAuthCode);
        }
 
        String tc = entity.getTc();
        if (tc != null) {
            stmt.bindString(48, tc);
        }
 
        String arqc = entity.getArqc();
        if (arqc != null) {
            stmt.bindString(49, arqc);
        }
 
        String arpc = entity.getArpc();
        if (arpc != null) {
            stmt.bindString(50, arpc);
        }
 
        String tvr = entity.getTvr();
        if (tvr != null) {
            stmt.bindString(51, tvr);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(52, aid);
        }
 
        String emvAppLabel = entity.getEmvAppLabel();
        if (emvAppLabel != null) {
            stmt.bindString(53, emvAppLabel);
        }
 
        String emvAppName = entity.getEmvAppName();
        if (emvAppName != null) {
            stmt.bindString(54, emvAppName);
        }
 
        String tsi = entity.getTsi();
        if (tsi != null) {
            stmt.bindString(55, tsi);
        }
 
        String atc = entity.getAtc();
        if (atc != null) {
            stmt.bindString(56, atc);
        }
 
        String field22 = entity.getField22();
        if (field22 != null) {
            stmt.bindString(57, field22);
        }
 
        String field62 = entity.getField62();
        if (field62 != null) {
            stmt.bindString(58, field62);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DupTransdata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(2, orderNo);
        }
 
        String orderNodis = entity.getOrderNodis();
        if (orderNodis != null) {
            stmt.bindString(3, orderNodis);
        }
 
        String amount = entity.getAmount();
        if (amount != null) {
            stmt.bindString(4, amount);
        }
 
        String tipAmount = entity.getTipAmount();
        if (tipAmount != null) {
            stmt.bindString(5, tipAmount);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(6, balance);
        }
 
        String balanceFlag = entity.getBalanceFlag();
        if (balanceFlag != null) {
            stmt.bindString(7, balanceFlag);
        }
        stmt.bindLong(8, entity.getTransNo());
        stmt.bindLong(9, entity.getOrigTransNo());
        stmt.bindLong(10, entity.getBatchNo());
 
        String transType = entity.getTransType();
        if (transType != null) {
            stmt.bindString(11, transType);
        }
 
        String merchID = entity.getMerchID();
        if (merchID != null) {
            stmt.bindString(12, merchID);
        }
 
        String origProcCode = entity.getOrigProcCode();
        if (origProcCode != null) {
            stmt.bindString(13, origProcCode);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(14, qrCode);
        }
 
        String origQrCode = entity.getOrigQrCode();
        if (origQrCode != null) {
            stmt.bindString(15, origQrCode);
        }
 
        String qrVoucher = entity.getQrVoucher();
        if (qrVoucher != null) {
            stmt.bindString(16, qrVoucher);
        }
 
        String origQrVoucher = entity.getOrigQrVoucher();
        if (origQrVoucher != null) {
            stmt.bindString(17, origQrVoucher);
        }
 
        String transState = entity.getTransState();
        if (transState != null) {
            stmt.bindString(18, transState);
        }
 
        String oper = entity.getOper();
        if (oper != null) {
            stmt.bindString(19, oper);
        }
 
        String track1 = entity.getTrack1();
        if (track1 != null) {
            stmt.bindString(20, track1);
        }
 
        String track2 = entity.getTrack2();
        if (track2 != null) {
            stmt.bindString(21, track2);
        }
 
        String track3 = entity.getTrack3();
        if (track3 != null) {
            stmt.bindString(22, track3);
        }
        stmt.bindLong(23, entity.getIsEncTrack() ? 1L: 0L);
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(24, reason);
        }
 
        String reserved = entity.getReserved();
        if (reserved != null) {
            stmt.bindString(25, reserved);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(26, datetime);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(27, time);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(28, date);
        }
 
        String termID = entity.getTermID();
        if (termID != null) {
            stmt.bindString(29, termID);
        }
 
        String pan = entity.getPan();
        if (pan != null) {
            stmt.bindString(30, pan);
        }
 
        String expDate = entity.getExpDate();
        if (expDate != null) {
            stmt.bindString(31, expDate);
        }
 
        String cardSerialNo = entity.getCardSerialNo();
        if (cardSerialNo != null) {
            stmt.bindString(32, cardSerialNo);
        }
        stmt.bindLong(33, entity.getEnterMode());
        stmt.bindLong(34, entity.getHasPin() ? 1L: 0L);
 
        String sendIccData = entity.getSendIccData();
        if (sendIccData != null) {
            stmt.bindString(35, sendIccData);
        }
 
        String dupIccData = entity.getDupIccData();
        if (dupIccData != null) {
            stmt.bindString(36, dupIccData);
        }
 
        String origDate = entity.getOrigDate();
        if (origDate != null) {
            stmt.bindString(37, origDate);
        }
 
        String ICPositiveData = entity.getICPositiveData();
        if (ICPositiveData != null) {
            stmt.bindString(38, ICPositiveData);
        }
 
        String tag9F5B = entity.getTag9F5B();
        if (tag9F5B != null) {
            stmt.bindString(39, tag9F5B);
        }
 
        String responseCode = entity.getResponseCode();
        if (responseCode != null) {
            stmt.bindString(40, responseCode);
        }
 
        String responseMsg = entity.getResponseMsg();
        if (responseMsg != null) {
            stmt.bindString(41, responseMsg);
        }
 
        String settleDate = entity.getSettleDate();
        if (settleDate != null) {
            stmt.bindString(42, settleDate);
        }
 
        String acqCenterCode = entity.getAcqCenterCode();
        if (acqCenterCode != null) {
            stmt.bindString(43, acqCenterCode);
        }
 
        String refNo = entity.getRefNo();
        if (refNo != null) {
            stmt.bindString(44, refNo);
        }
 
        String origRefNo = entity.getOrigRefNo();
        if (origRefNo != null) {
            stmt.bindString(45, origRefNo);
        }
 
        String authCode = entity.getAuthCode();
        if (authCode != null) {
            stmt.bindString(46, authCode);
        }
 
        String origAuthCode = entity.getOrigAuthCode();
        if (origAuthCode != null) {
            stmt.bindString(47, origAuthCode);
        }
 
        String tc = entity.getTc();
        if (tc != null) {
            stmt.bindString(48, tc);
        }
 
        String arqc = entity.getArqc();
        if (arqc != null) {
            stmt.bindString(49, arqc);
        }
 
        String arpc = entity.getArpc();
        if (arpc != null) {
            stmt.bindString(50, arpc);
        }
 
        String tvr = entity.getTvr();
        if (tvr != null) {
            stmt.bindString(51, tvr);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(52, aid);
        }
 
        String emvAppLabel = entity.getEmvAppLabel();
        if (emvAppLabel != null) {
            stmt.bindString(53, emvAppLabel);
        }
 
        String emvAppName = entity.getEmvAppName();
        if (emvAppName != null) {
            stmt.bindString(54, emvAppName);
        }
 
        String tsi = entity.getTsi();
        if (tsi != null) {
            stmt.bindString(55, tsi);
        }
 
        String atc = entity.getAtc();
        if (atc != null) {
            stmt.bindString(56, atc);
        }
 
        String field22 = entity.getField22();
        if (field22 != null) {
            stmt.bindString(57, field22);
        }
 
        String field62 = entity.getField62();
        if (field62 != null) {
            stmt.bindString(58, field62);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DupTransdata readEntity(Cursor cursor, int offset) {
        DupTransdata entity = new DupTransdata( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // orderNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // orderNodis
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // amount
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tipAmount
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // balance
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // balanceFlag
            cursor.getLong(offset + 7), // transNo
            cursor.getLong(offset + 8), // origTransNo
            cursor.getLong(offset + 9), // batchNo
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // transType
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // merchID
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // origProcCode
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // qrCode
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // origQrCode
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // qrVoucher
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // origQrVoucher
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // transState
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // oper
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // track1
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // track2
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // track3
            cursor.getShort(offset + 22) != 0, // isEncTrack
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // reason
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // reserved
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // datetime
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // time
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // date
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // termID
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // pan
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // expDate
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // cardSerialNo
            cursor.getInt(offset + 32), // enterMode
            cursor.getShort(offset + 33) != 0, // hasPin
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // sendIccData
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // dupIccData
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // origDate
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // ICPositiveData
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // tag9F5B
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // responseCode
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // responseMsg
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // settleDate
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // acqCenterCode
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // refNo
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // origRefNo
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // authCode
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // origAuthCode
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // tc
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // arqc
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // arpc
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // tvr
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // aid
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // emvAppLabel
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // emvAppName
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // tsi
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // atc
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // field22
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57) // field62
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DupTransdata entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOrderNodis(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAmount(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTipAmount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBalance(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBalanceFlag(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTransNo(cursor.getLong(offset + 7));
        entity.setOrigTransNo(cursor.getLong(offset + 8));
        entity.setBatchNo(cursor.getLong(offset + 9));
        entity.setTransType(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMerchID(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOrigProcCode(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setQrCode(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setOrigQrCode(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setQrVoucher(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setOrigQrVoucher(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTransState(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setOper(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTrack1(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTrack2(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTrack3(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setIsEncTrack(cursor.getShort(offset + 22) != 0);
        entity.setReason(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setReserved(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setDatetime(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setTime(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setDate(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setTermID(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setPan(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setExpDate(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setCardSerialNo(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setEnterMode(cursor.getInt(offset + 32));
        entity.setHasPin(cursor.getShort(offset + 33) != 0);
        entity.setSendIccData(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setDupIccData(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setOrigDate(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setICPositiveData(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setTag9F5B(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setResponseCode(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setResponseMsg(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setSettleDate(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setAcqCenterCode(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setRefNo(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setOrigRefNo(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setAuthCode(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setOrigAuthCode(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setTc(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setArqc(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setArpc(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setTvr(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setAid(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setEmvAppLabel(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setEmvAppName(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setTsi(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setAtc(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setField22(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setField62(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DupTransdata entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DupTransdata entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DupTransdata entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
