package com.topwise.premierpay.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.topwise.premierpay.daoutils.entity.ScriptTransdata;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCRIPT_TRANSDATA".
*/
public class ScriptTransdataDao extends AbstractDao<ScriptTransdata, Long> {

    public static final String TABLENAME = "SCRIPT_TRANSDATA";

    /**
     * Properties of entity ScriptTransdata.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ScriptData = new Property(1, String.class, "scriptData", false, "SCRIPT_DATA");
        public final static Property TransNo = new Property(2, long.class, "transNo", false, "TRANS_NO");
        public final static Property OrigTransNo = new Property(3, long.class, "origTransNo", false, "ORIG_TRANS_NO");
        public final static Property OrigBatchNo = new Property(4, long.class, "origBatchNo", false, "ORIG_BATCH_NO");
        public final static Property OrigRefNo = new Property(5, String.class, "origRefNo", false, "ORIG_REF_NO");
        public final static Property OrigAuthCode = new Property(6, String.class, "origAuthCode", false, "ORIG_AUTH_CODE");
        public final static Property OrigDate = new Property(7, String.class, "origDate", false, "ORIG_DATE");
        public final static Property OrigAmount = new Property(8, String.class, "origAmount", false, "ORIG_AMOUNT");
        public final static Property OrigF62 = new Property(9, String.class, "origF62", false, "ORIG_F62");
        public final static Property Datetime = new Property(10, String.class, "datetime", false, "DATETIME");
        public final static Property TermID = new Property(11, String.class, "termID", false, "TERM_ID");
        public final static Property MerchID = new Property(12, String.class, "merchID", false, "MERCH_ID");
    }


    public ScriptTransdataDao(DaoConfig config) {
        super(config);
    }
    
    public ScriptTransdataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCRIPT_TRANSDATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SCRIPT_DATA\" TEXT," + // 1: scriptData
                "\"TRANS_NO\" INTEGER NOT NULL ," + // 2: transNo
                "\"ORIG_TRANS_NO\" INTEGER NOT NULL ," + // 3: origTransNo
                "\"ORIG_BATCH_NO\" INTEGER NOT NULL ," + // 4: origBatchNo
                "\"ORIG_REF_NO\" TEXT," + // 5: origRefNo
                "\"ORIG_AUTH_CODE\" TEXT," + // 6: origAuthCode
                "\"ORIG_DATE\" TEXT," + // 7: origDate
                "\"ORIG_AMOUNT\" TEXT," + // 8: origAmount
                "\"ORIG_F62\" TEXT," + // 9: origF62
                "\"DATETIME\" TEXT," + // 10: datetime
                "\"TERM_ID\" TEXT," + // 11: termID
                "\"MERCH_ID\" TEXT);"); // 12: merchID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCRIPT_TRANSDATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ScriptTransdata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String scriptData = entity.getScriptData();
        if (scriptData != null) {
            stmt.bindString(2, scriptData);
        }
        stmt.bindLong(3, entity.getTransNo());
        stmt.bindLong(4, entity.getOrigTransNo());
        stmt.bindLong(5, entity.getOrigBatchNo());
 
        String origRefNo = entity.getOrigRefNo();
        if (origRefNo != null) {
            stmt.bindString(6, origRefNo);
        }
 
        String origAuthCode = entity.getOrigAuthCode();
        if (origAuthCode != null) {
            stmt.bindString(7, origAuthCode);
        }
 
        String origDate = entity.getOrigDate();
        if (origDate != null) {
            stmt.bindString(8, origDate);
        }
 
        String origAmount = entity.getOrigAmount();
        if (origAmount != null) {
            stmt.bindString(9, origAmount);
        }
 
        String origF62 = entity.getOrigF62();
        if (origF62 != null) {
            stmt.bindString(10, origF62);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(11, datetime);
        }
 
        String termID = entity.getTermID();
        if (termID != null) {
            stmt.bindString(12, termID);
        }
 
        String merchID = entity.getMerchID();
        if (merchID != null) {
            stmt.bindString(13, merchID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ScriptTransdata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String scriptData = entity.getScriptData();
        if (scriptData != null) {
            stmt.bindString(2, scriptData);
        }
        stmt.bindLong(3, entity.getTransNo());
        stmt.bindLong(4, entity.getOrigTransNo());
        stmt.bindLong(5, entity.getOrigBatchNo());
 
        String origRefNo = entity.getOrigRefNo();
        if (origRefNo != null) {
            stmt.bindString(6, origRefNo);
        }
 
        String origAuthCode = entity.getOrigAuthCode();
        if (origAuthCode != null) {
            stmt.bindString(7, origAuthCode);
        }
 
        String origDate = entity.getOrigDate();
        if (origDate != null) {
            stmt.bindString(8, origDate);
        }
 
        String origAmount = entity.getOrigAmount();
        if (origAmount != null) {
            stmt.bindString(9, origAmount);
        }
 
        String origF62 = entity.getOrigF62();
        if (origF62 != null) {
            stmt.bindString(10, origF62);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(11, datetime);
        }
 
        String termID = entity.getTermID();
        if (termID != null) {
            stmt.bindString(12, termID);
        }
 
        String merchID = entity.getMerchID();
        if (merchID != null) {
            stmt.bindString(13, merchID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ScriptTransdata readEntity(Cursor cursor, int offset) {
        ScriptTransdata entity = new ScriptTransdata( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // scriptData
            cursor.getLong(offset + 2), // transNo
            cursor.getLong(offset + 3), // origTransNo
            cursor.getLong(offset + 4), // origBatchNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // origRefNo
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // origAuthCode
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // origDate
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // origAmount
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // origF62
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // datetime
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // termID
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // merchID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ScriptTransdata entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setScriptData(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTransNo(cursor.getLong(offset + 2));
        entity.setOrigTransNo(cursor.getLong(offset + 3));
        entity.setOrigBatchNo(cursor.getLong(offset + 4));
        entity.setOrigRefNo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrigAuthCode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOrigDate(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setOrigAmount(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOrigF62(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDatetime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTermID(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setMerchID(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ScriptTransdata entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ScriptTransdata entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ScriptTransdata entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
