package com.topwise.premierpay.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.topwise.premierpay.trans.model.TestParam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_PARAM".
*/
public class TestParamDao extends AbstractDao<TestParam, Long> {

    public static final String TABLENAME = "TEST_PARAM";

    /**
     * Properties of entity TestParam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CommType = new Property(1, int.class, "commType", false, "COMM_TYPE");
        public final static Property TotalNum = new Property(2, int.class, "totalNum", false, "TOTAL_NUM");
        public final static Property IntervalTime = new Property(3, int.class, "intervalTime", false, "INTERVAL_TIME");
        public final static Property DelayTime = new Property(4, int.class, "delayTime", false, "DELAY_TIME");
        public final static Property IntervalMode = new Property(5, int.class, "intervalMode", false, "INTERVAL_MODE");
        public final static Property EachTransTime = new Property(6, int.class, "eachTransTime", false, "EACH_TRANS_TIME");
    }


    public TestParamDao(DaoConfig config) {
        super(config);
    }
    
    public TestParamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_PARAM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COMM_TYPE\" INTEGER NOT NULL ," + // 1: commType
                "\"TOTAL_NUM\" INTEGER NOT NULL ," + // 2: totalNum
                "\"INTERVAL_TIME\" INTEGER NOT NULL ," + // 3: intervalTime
                "\"DELAY_TIME\" INTEGER NOT NULL ," + // 4: delayTime
                "\"INTERVAL_MODE\" INTEGER NOT NULL ," + // 5: intervalMode
                "\"EACH_TRANS_TIME\" INTEGER NOT NULL );"); // 6: eachTransTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_PARAM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestParam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCommType());
        stmt.bindLong(3, entity.getTotalNum());
        stmt.bindLong(4, entity.getIntervalTime());
        stmt.bindLong(5, entity.getDelayTime());
        stmt.bindLong(6, entity.getIntervalMode());
        stmt.bindLong(7, entity.getEachTransTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestParam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCommType());
        stmt.bindLong(3, entity.getTotalNum());
        stmt.bindLong(4, entity.getIntervalTime());
        stmt.bindLong(5, entity.getDelayTime());
        stmt.bindLong(6, entity.getIntervalMode());
        stmt.bindLong(7, entity.getEachTransTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestParam readEntity(Cursor cursor, int offset) {
        TestParam entity = new TestParam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // commType
            cursor.getInt(offset + 2), // totalNum
            cursor.getInt(offset + 3), // intervalTime
            cursor.getInt(offset + 4), // delayTime
            cursor.getInt(offset + 5), // intervalMode
            cursor.getInt(offset + 6) // eachTransTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestParam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCommType(cursor.getInt(offset + 1));
        entity.setTotalNum(cursor.getInt(offset + 2));
        entity.setIntervalTime(cursor.getInt(offset + 3));
        entity.setDelayTime(cursor.getInt(offset + 4));
        entity.setIntervalMode(cursor.getInt(offset + 5));
        entity.setEachTransTime(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestParam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestParam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestParam entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
