package com.topwise.premierpay.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.topwise.premierpay.daoutils.entity.TotaTransdata;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOTA_TRANSDATA".
*/
public class TotaTransdataDao extends AbstractDao<TotaTransdata, Long> {

    public static final String TABLENAME = "TOTA_TRANSDATA";

    /**
     * Properties of entity TotaTransdata.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MerchantID = new Property(1, String.class, "merchantID", false, "MERCHANT_ID");
        public final static Property TerminalID = new Property(2, String.class, "terminalID", false, "TERMINAL_ID");
        public final static Property OperatorID = new Property(3, String.class, "operatorID", false, "OPERATOR_ID");
        public final static Property BatchNo = new Property(4, String.class, "batchNo", false, "BATCH_NO");
        public final static Property Datetime = new Property(5, String.class, "datetime", false, "DATETIME");
        public final static Property BankNumberTotal = new Property(6, Long.class, "bankNumberTotal", false, "BANK_NUMBER_TOTAL");
        public final static Property BankAmountTotal = new Property(7, Long.class, "bankAmountTotal", false, "BANK_AMOUNT_TOTAL");
        public final static Property BankSaleNumberTotal = new Property(8, Long.class, "bankSaleNumberTotal", false, "BANK_SALE_NUMBER_TOTAL");
        public final static Property BankSaleAmountTotal = new Property(9, Long.class, "bankSaleAmountTotal", false, "BANK_SALE_AMOUNT_TOTAL");
        public final static Property BankVoidNumberTotal = new Property(10, Long.class, "bankVoidNumberTotal", false, "BANK_VOID_NUMBER_TOTAL");
        public final static Property BankVoidAmountTotal = new Property(11, Long.class, "bankVoidAmountTotal", false, "BANK_VOID_AMOUNT_TOTAL");
        public final static Property BankRefundNumberTotal = new Property(12, Long.class, "bankRefundNumberTotal", false, "BANK_REFUND_NUMBER_TOTAL");
        public final static Property BankRefundAmountTotal = new Property(13, Long.class, "bankRefundAmountTotal", false, "BANK_REFUND_AMOUNT_TOTAL");
        public final static Property QrNumberTotal = new Property(14, Long.class, "qrNumberTotal", false, "QR_NUMBER_TOTAL");
        public final static Property QrAmountTotal = new Property(15, Long.class, "qrAmountTotal", false, "QR_AMOUNT_TOTAL");
        public final static Property QrSaleNumberTotal = new Property(16, Long.class, "qrSaleNumberTotal", false, "QR_SALE_NUMBER_TOTAL");
        public final static Property QrSaleAmountTotal = new Property(17, Long.class, "qrSaleAmountTotal", false, "QR_SALE_AMOUNT_TOTAL");
        public final static Property QrVoidNumberTotal = new Property(18, Long.class, "qrVoidNumberTotal", false, "QR_VOID_NUMBER_TOTAL");
        public final static Property QrVoidAmountTotal = new Property(19, Long.class, "qrVoidAmountTotal", false, "QR_VOID_AMOUNT_TOTAL");
        public final static Property QrRefundNumberTotal = new Property(20, Long.class, "qrRefundNumberTotal", false, "QR_REFUND_NUMBER_TOTAL");
        public final static Property QrRefundAmountTotal = new Property(21, Long.class, "qrRefundAmountTotal", false, "QR_REFUND_AMOUNT_TOTAL");
        public final static Property AuthCmdNumberTotal = new Property(22, Long.class, "authCmdNumberTotal", false, "AUTH_CMD_NUMBER_TOTAL");
        public final static Property AuthCmdAmountTotal = new Property(23, Long.class, "authCmdAmountTotal", false, "AUTH_CMD_AMOUNT_TOTAL");
    }


    public TotaTransdataDao(DaoConfig config) {
        super(config);
    }
    
    public TotaTransdataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOTA_TRANSDATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MERCHANT_ID\" TEXT," + // 1: merchantID
                "\"TERMINAL_ID\" TEXT," + // 2: terminalID
                "\"OPERATOR_ID\" TEXT," + // 3: operatorID
                "\"BATCH_NO\" TEXT," + // 4: batchNo
                "\"DATETIME\" TEXT," + // 5: datetime
                "\"BANK_NUMBER_TOTAL\" INTEGER," + // 6: bankNumberTotal
                "\"BANK_AMOUNT_TOTAL\" INTEGER," + // 7: bankAmountTotal
                "\"BANK_SALE_NUMBER_TOTAL\" INTEGER," + // 8: bankSaleNumberTotal
                "\"BANK_SALE_AMOUNT_TOTAL\" INTEGER," + // 9: bankSaleAmountTotal
                "\"BANK_VOID_NUMBER_TOTAL\" INTEGER," + // 10: bankVoidNumberTotal
                "\"BANK_VOID_AMOUNT_TOTAL\" INTEGER," + // 11: bankVoidAmountTotal
                "\"BANK_REFUND_NUMBER_TOTAL\" INTEGER," + // 12: bankRefundNumberTotal
                "\"BANK_REFUND_AMOUNT_TOTAL\" INTEGER," + // 13: bankRefundAmountTotal
                "\"QR_NUMBER_TOTAL\" INTEGER," + // 14: qrNumberTotal
                "\"QR_AMOUNT_TOTAL\" INTEGER," + // 15: qrAmountTotal
                "\"QR_SALE_NUMBER_TOTAL\" INTEGER," + // 16: qrSaleNumberTotal
                "\"QR_SALE_AMOUNT_TOTAL\" INTEGER," + // 17: qrSaleAmountTotal
                "\"QR_VOID_NUMBER_TOTAL\" INTEGER," + // 18: qrVoidNumberTotal
                "\"QR_VOID_AMOUNT_TOTAL\" INTEGER," + // 19: qrVoidAmountTotal
                "\"QR_REFUND_NUMBER_TOTAL\" INTEGER," + // 20: qrRefundNumberTotal
                "\"QR_REFUND_AMOUNT_TOTAL\" INTEGER," + // 21: qrRefundAmountTotal
                "\"AUTH_CMD_NUMBER_TOTAL\" INTEGER," + // 22: authCmdNumberTotal
                "\"AUTH_CMD_AMOUNT_TOTAL\" INTEGER);"); // 23: authCmdAmountTotal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOTA_TRANSDATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TotaTransdata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String merchantID = entity.getMerchantID();
        if (merchantID != null) {
            stmt.bindString(2, merchantID);
        }
 
        String terminalID = entity.getTerminalID();
        if (terminalID != null) {
            stmt.bindString(3, terminalID);
        }
 
        String operatorID = entity.getOperatorID();
        if (operatorID != null) {
            stmt.bindString(4, operatorID);
        }
 
        String batchNo = entity.getBatchNo();
        if (batchNo != null) {
            stmt.bindString(5, batchNo);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(6, datetime);
        }
 
        Long bankNumberTotal = entity.getBankNumberTotal();
        if (bankNumberTotal != null) {
            stmt.bindLong(7, bankNumberTotal);
        }
 
        Long bankAmountTotal = entity.getBankAmountTotal();
        if (bankAmountTotal != null) {
            stmt.bindLong(8, bankAmountTotal);
        }
 
        Long bankSaleNumberTotal = entity.getBankSaleNumberTotal();
        if (bankSaleNumberTotal != null) {
            stmt.bindLong(9, bankSaleNumberTotal);
        }
 
        Long bankSaleAmountTotal = entity.getBankSaleAmountTotal();
        if (bankSaleAmountTotal != null) {
            stmt.bindLong(10, bankSaleAmountTotal);
        }
 
        Long bankVoidNumberTotal = entity.getBankVoidNumberTotal();
        if (bankVoidNumberTotal != null) {
            stmt.bindLong(11, bankVoidNumberTotal);
        }
 
        Long bankVoidAmountTotal = entity.getBankVoidAmountTotal();
        if (bankVoidAmountTotal != null) {
            stmt.bindLong(12, bankVoidAmountTotal);
        }
 
        Long bankRefundNumberTotal = entity.getBankRefundNumberTotal();
        if (bankRefundNumberTotal != null) {
            stmt.bindLong(13, bankRefundNumberTotal);
        }
 
        Long bankRefundAmountTotal = entity.getBankRefundAmountTotal();
        if (bankRefundAmountTotal != null) {
            stmt.bindLong(14, bankRefundAmountTotal);
        }
 
        Long qrNumberTotal = entity.getQrNumberTotal();
        if (qrNumberTotal != null) {
            stmt.bindLong(15, qrNumberTotal);
        }
 
        Long qrAmountTotal = entity.getQrAmountTotal();
        if (qrAmountTotal != null) {
            stmt.bindLong(16, qrAmountTotal);
        }
 
        Long qrSaleNumberTotal = entity.getQrSaleNumberTotal();
        if (qrSaleNumberTotal != null) {
            stmt.bindLong(17, qrSaleNumberTotal);
        }
 
        Long qrSaleAmountTotal = entity.getQrSaleAmountTotal();
        if (qrSaleAmountTotal != null) {
            stmt.bindLong(18, qrSaleAmountTotal);
        }
 
        Long qrVoidNumberTotal = entity.getQrVoidNumberTotal();
        if (qrVoidNumberTotal != null) {
            stmt.bindLong(19, qrVoidNumberTotal);
        }
 
        Long qrVoidAmountTotal = entity.getQrVoidAmountTotal();
        if (qrVoidAmountTotal != null) {
            stmt.bindLong(20, qrVoidAmountTotal);
        }
 
        Long qrRefundNumberTotal = entity.getQrRefundNumberTotal();
        if (qrRefundNumberTotal != null) {
            stmt.bindLong(21, qrRefundNumberTotal);
        }
 
        Long qrRefundAmountTotal = entity.getQrRefundAmountTotal();
        if (qrRefundAmountTotal != null) {
            stmt.bindLong(22, qrRefundAmountTotal);
        }
 
        Long authCmdNumberTotal = entity.getAuthCmdNumberTotal();
        if (authCmdNumberTotal != null) {
            stmt.bindLong(23, authCmdNumberTotal);
        }
 
        Long authCmdAmountTotal = entity.getAuthCmdAmountTotal();
        if (authCmdAmountTotal != null) {
            stmt.bindLong(24, authCmdAmountTotal);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TotaTransdata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String merchantID = entity.getMerchantID();
        if (merchantID != null) {
            stmt.bindString(2, merchantID);
        }
 
        String terminalID = entity.getTerminalID();
        if (terminalID != null) {
            stmt.bindString(3, terminalID);
        }
 
        String operatorID = entity.getOperatorID();
        if (operatorID != null) {
            stmt.bindString(4, operatorID);
        }
 
        String batchNo = entity.getBatchNo();
        if (batchNo != null) {
            stmt.bindString(5, batchNo);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(6, datetime);
        }
 
        Long bankNumberTotal = entity.getBankNumberTotal();
        if (bankNumberTotal != null) {
            stmt.bindLong(7, bankNumberTotal);
        }
 
        Long bankAmountTotal = entity.getBankAmountTotal();
        if (bankAmountTotal != null) {
            stmt.bindLong(8, bankAmountTotal);
        }
 
        Long bankSaleNumberTotal = entity.getBankSaleNumberTotal();
        if (bankSaleNumberTotal != null) {
            stmt.bindLong(9, bankSaleNumberTotal);
        }
 
        Long bankSaleAmountTotal = entity.getBankSaleAmountTotal();
        if (bankSaleAmountTotal != null) {
            stmt.bindLong(10, bankSaleAmountTotal);
        }
 
        Long bankVoidNumberTotal = entity.getBankVoidNumberTotal();
        if (bankVoidNumberTotal != null) {
            stmt.bindLong(11, bankVoidNumberTotal);
        }
 
        Long bankVoidAmountTotal = entity.getBankVoidAmountTotal();
        if (bankVoidAmountTotal != null) {
            stmt.bindLong(12, bankVoidAmountTotal);
        }
 
        Long bankRefundNumberTotal = entity.getBankRefundNumberTotal();
        if (bankRefundNumberTotal != null) {
            stmt.bindLong(13, bankRefundNumberTotal);
        }
 
        Long bankRefundAmountTotal = entity.getBankRefundAmountTotal();
        if (bankRefundAmountTotal != null) {
            stmt.bindLong(14, bankRefundAmountTotal);
        }
 
        Long qrNumberTotal = entity.getQrNumberTotal();
        if (qrNumberTotal != null) {
            stmt.bindLong(15, qrNumberTotal);
        }
 
        Long qrAmountTotal = entity.getQrAmountTotal();
        if (qrAmountTotal != null) {
            stmt.bindLong(16, qrAmountTotal);
        }
 
        Long qrSaleNumberTotal = entity.getQrSaleNumberTotal();
        if (qrSaleNumberTotal != null) {
            stmt.bindLong(17, qrSaleNumberTotal);
        }
 
        Long qrSaleAmountTotal = entity.getQrSaleAmountTotal();
        if (qrSaleAmountTotal != null) {
            stmt.bindLong(18, qrSaleAmountTotal);
        }
 
        Long qrVoidNumberTotal = entity.getQrVoidNumberTotal();
        if (qrVoidNumberTotal != null) {
            stmt.bindLong(19, qrVoidNumberTotal);
        }
 
        Long qrVoidAmountTotal = entity.getQrVoidAmountTotal();
        if (qrVoidAmountTotal != null) {
            stmt.bindLong(20, qrVoidAmountTotal);
        }
 
        Long qrRefundNumberTotal = entity.getQrRefundNumberTotal();
        if (qrRefundNumberTotal != null) {
            stmt.bindLong(21, qrRefundNumberTotal);
        }
 
        Long qrRefundAmountTotal = entity.getQrRefundAmountTotal();
        if (qrRefundAmountTotal != null) {
            stmt.bindLong(22, qrRefundAmountTotal);
        }
 
        Long authCmdNumberTotal = entity.getAuthCmdNumberTotal();
        if (authCmdNumberTotal != null) {
            stmt.bindLong(23, authCmdNumberTotal);
        }
 
        Long authCmdAmountTotal = entity.getAuthCmdAmountTotal();
        if (authCmdAmountTotal != null) {
            stmt.bindLong(24, authCmdAmountTotal);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TotaTransdata readEntity(Cursor cursor, int offset) {
        TotaTransdata entity = new TotaTransdata( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // merchantID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // terminalID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // operatorID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // batchNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // datetime
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // bankNumberTotal
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // bankAmountTotal
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // bankSaleNumberTotal
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // bankSaleAmountTotal
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // bankVoidNumberTotal
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // bankVoidAmountTotal
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12), // bankRefundNumberTotal
            cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13), // bankRefundAmountTotal
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14), // qrNumberTotal
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15), // qrAmountTotal
            cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16), // qrSaleNumberTotal
            cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17), // qrSaleAmountTotal
            cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18), // qrVoidNumberTotal
            cursor.isNull(offset + 19) ? null : cursor.getLong(offset + 19), // qrVoidAmountTotal
            cursor.isNull(offset + 20) ? null : cursor.getLong(offset + 20), // qrRefundNumberTotal
            cursor.isNull(offset + 21) ? null : cursor.getLong(offset + 21), // qrRefundAmountTotal
            cursor.isNull(offset + 22) ? null : cursor.getLong(offset + 22), // authCmdNumberTotal
            cursor.isNull(offset + 23) ? null : cursor.getLong(offset + 23) // authCmdAmountTotal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TotaTransdata entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMerchantID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTerminalID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOperatorID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBatchNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDatetime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBankNumberTotal(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setBankAmountTotal(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setBankSaleNumberTotal(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setBankSaleAmountTotal(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setBankVoidNumberTotal(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setBankVoidAmountTotal(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setBankRefundNumberTotal(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
        entity.setBankRefundAmountTotal(cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13));
        entity.setQrNumberTotal(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
        entity.setQrAmountTotal(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
        entity.setQrSaleNumberTotal(cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16));
        entity.setQrSaleAmountTotal(cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17));
        entity.setQrVoidNumberTotal(cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18));
        entity.setQrVoidAmountTotal(cursor.isNull(offset + 19) ? null : cursor.getLong(offset + 19));
        entity.setQrRefundNumberTotal(cursor.isNull(offset + 20) ? null : cursor.getLong(offset + 20));
        entity.setQrRefundAmountTotal(cursor.isNull(offset + 21) ? null : cursor.getLong(offset + 21));
        entity.setAuthCmdNumberTotal(cursor.isNull(offset + 22) ? null : cursor.getLong(offset + 22));
        entity.setAuthCmdAmountTotal(cursor.isNull(offset + 23) ? null : cursor.getLong(offset + 23));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TotaTransdata entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TotaTransdata entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TotaTransdata entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
