package com.topwise.premierpay.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.topwise.premierpay.trans.model.TransData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANS_DATA".
*/
public class TransDataDao extends AbstractDao<TransData, Long> {

    public static final String TABLENAME = "TRANS_DATA";

    /**
     * Properties of entity TransData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderNo = new Property(1, String.class, "orderNo", false, "ORDER_NO");
        public final static Property OrderNodis = new Property(2, String.class, "orderNodis", false, "ORDER_NODIS");
        public final static Property Amount = new Property(3, String.class, "amount", false, "AMOUNT");
        public final static Property CardAmount = new Property(4, String.class, "cardAmount", false, "CARD_AMOUNT");
        public final static Property CashAmount = new Property(5, String.class, "cashAmount", false, "CASH_AMOUNT");
        public final static Property TipAmount = new Property(6, String.class, "tipAmount", false, "TIP_AMOUNT");
        public final static Property Balance = new Property(7, String.class, "balance", false, "BALANCE");
        public final static Property BalanceFlag = new Property(8, String.class, "balanceFlag", false, "BALANCE_FLAG");
        public final static Property EmvResult = new Property(9, byte.class, "emvResult", false, "EMV_RESULT");
        public final static Property InterOrgCode = new Property(10, String.class, "interOrgCode", false, "INTER_ORG_CODE");
        public final static Property TransNo = new Property(11, long.class, "transNo", false, "TRANS_NO");
        public final static Property OrigTransNo = new Property(12, long.class, "origTransNo", false, "ORIG_TRANS_NO");
        public final static Property BatchNo = new Property(13, long.class, "batchNo", false, "BATCH_NO");
        public final static Property OrigBatchNo = new Property(14, long.class, "origBatchNo", false, "ORIG_BATCH_NO");
        public final static Property TransType = new Property(15, String.class, "transType", false, "TRANS_TYPE");
        public final static Property OrigTransType = new Property(16, String.class, "origTransType", false, "ORIG_TRANS_TYPE");
        public final static Property MerchID = new Property(17, String.class, "merchID", false, "MERCH_ID");
        public final static Property Mcc = new Property(18, String.class, "mcc", false, "MCC");
        public final static Property IsUpload = new Property(19, boolean.class, "isUpload", false, "IS_UPLOAD");
        public final static Property TransState = new Property(20, String.class, "transState", false, "TRANS_STATE");
        public final static Property Oper = new Property(21, String.class, "oper", false, "OPER");
        public final static Property Track1 = new Property(22, String.class, "track1", false, "TRACK1");
        public final static Property Track2 = new Property(23, String.class, "track2", false, "TRACK2");
        public final static Property Track3 = new Property(24, String.class, "track3", false, "TRACK3");
        public final static Property IsEncTrack = new Property(25, boolean.class, "isEncTrack", false, "IS_ENC_TRACK");
        public final static Property Reason = new Property(26, String.class, "reason", false, "REASON");
        public final static Property Reserved = new Property(27, String.class, "reserved", false, "RESERVED");
        public final static Property Datetime = new Property(28, String.class, "datetime", false, "DATETIME");
        public final static Property UnNum = new Property(29, String.class, "UnNum", false, "UN_NUM");
        public final static Property Time = new Property(30, String.class, "time", false, "TIME");
        public final static Property Date = new Property(31, String.class, "date", false, "DATE");
        public final static Property TermID = new Property(32, String.class, "termID", false, "TERM_ID");
        public final static Property Pan = new Property(33, String.class, "pan", false, "PAN");
        public final static Property ExpDate = new Property(34, String.class, "expDate", false, "EXP_DATE");
        public final static Property CardSerialNo = new Property(35, String.class, "cardSerialNo", false, "CARD_SERIAL_NO");
        public final static Property EnterMode = new Property(36, int.class, "enterMode", false, "ENTER_MODE");
        public final static Property HasPin = new Property(37, boolean.class, "hasPin", false, "HAS_PIN");
        public final static Property SendIccData = new Property(38, String.class, "sendIccData", false, "SEND_ICC_DATA");
        public final static Property ScriptTag = new Property(39, String.class, "scriptTag", false, "SCRIPT_TAG");
        public final static Property DupIccData = new Property(40, String.class, "dupIccData", false, "DUP_ICC_DATA");
        public final static Property IsOnlineTrans = new Property(41, boolean.class, "isOnlineTrans", false, "IS_ONLINE_TRANS");
        public final static Property OrigDate = new Property(42, String.class, "origDate", false, "ORIG_DATE");
        public final static Property OrigTime = new Property(43, String.class, "origTime", false, "ORIG_TIME");
        public final static Property IsserCode = new Property(44, String.class, "isserCode", false, "ISSER_CODE");
        public final static Property AcqCode = new Property(45, String.class, "acqCode", false, "ACQ_CODE");
        public final static Property IsSupportBypass = new Property(46, boolean.class, "isSupportBypass", false, "IS_SUPPORT_BYPASS");
        public final static Property IssuerResp = new Property(47, String.class, "issuerResp", false, "ISSUER_RESP");
        public final static Property CenterResp = new Property(48, String.class, "centerResp", false, "CENTER_RESP");
        public final static Property RecvBankResp = new Property(49, String.class, "recvBankResp", false, "RECV_BANK_RESP");
        public final static Property ICPositiveData = new Property(50, String.class, "ICPositiveData", false, "ICPOSITIVE_DATA");
        public final static Property ResponseCode = new Property(51, String.class, "responseCode", false, "RESPONSE_CODE");
        public final static Property ResponseMsg = new Property(52, String.class, "responseMsg", false, "RESPONSE_MSG");
        public final static Property SettleDate = new Property(53, String.class, "settleDate", false, "SETTLE_DATE");
        public final static Property AcqCenterCode = new Property(54, String.class, "acqCenterCode", false, "ACQ_CENTER_CODE");
        public final static Property RefNo = new Property(55, String.class, "refNo", false, "REF_NO");
        public final static Property OrigRefNo = new Property(56, String.class, "origRefNo", false, "ORIG_REF_NO");
        public final static Property AuthCode = new Property(57, String.class, "authCode", false, "AUTH_CODE");
        public final static Property OrigAuthCode = new Property(58, String.class, "origAuthCode", false, "ORIG_AUTH_CODE");
        public final static Property Tc = new Property(59, String.class, "tc", false, "TC");
        public final static Property Arqc = new Property(60, String.class, "arqc", false, "ARQC");
        public final static Property Arpc = new Property(61, String.class, "arpc", false, "ARPC");
        public final static Property Tvr = new Property(62, String.class, "tvr", false, "TVR");
        public final static Property Aid = new Property(63, String.class, "aid", false, "AID");
        public final static Property EmvAppLabel = new Property(64, String.class, "emvAppLabel", false, "EMV_APP_LABEL");
        public final static Property EmvAppName = new Property(65, String.class, "emvAppName", false, "EMV_APP_NAME");
        public final static Property Tsi = new Property(66, String.class, "tsi", false, "TSI");
        public final static Property Atc = new Property(67, String.class, "atc", false, "ATC");
        public final static Property OrigProcCode = new Property(68, String.class, "origProcCode", false, "ORIG_PROC_CODE");
        public final static Property QrCode = new Property(69, String.class, "qrCode", false, "QR_CODE");
        public final static Property OrigQrCode = new Property(70, String.class, "origQrCode", false, "ORIG_QR_CODE");
        public final static Property QrVoucher = new Property(71, String.class, "qrVoucher", false, "QR_VOUCHER");
        public final static Property OrigQrVoucher = new Property(72, String.class, "origQrVoucher", false, "ORIG_QR_VOUCHER");
        public final static Property PinKsn = new Property(73, String.class, "pinKsn", false, "PIN_KSN");
        public final static Property DataKsn = new Property(74, String.class, "dataKsn", false, "DATA_KSN");
        public final static Property Field52 = new Property(75, String.class, "field52", false, "FIELD52");
        public final static Property Field58 = new Property(76, String.class, "field58", false, "FIELD58");
        public final static Property Field22 = new Property(77, String.class, "field22", false, "FIELD22");
        public final static Property ProcCode = new Property(78, String.class, "procCode", false, "PROC_CODE");
        public final static Property CardHolderName = new Property(79, String.class, "cardHolderName", false, "CARD_HOLDER_NAME");
        public final static Property ElecSignature = new Property(80, String.class, "ElecSignature", false, "ELEC_SIGNATURE");
        public final static Property KernelType = new Property(81, int.class, "kernelType", false, "KERNEL_TYPE");
        public final static Property NeedScript = new Property(82, boolean.class, "needScript", false, "NEED_SCRIPT");
        public final static Property Tag71 = new Property(83, String.class, "tag71", false, "TAG71");
        public final static Property Tag72 = new Property(84, String.class, "tag72", false, "TAG72");
        public final static Property Tag8A = new Property(85, String.class, "tag8A", false, "TAG8_A");
        public final static Property Tag91 = new Property(86, String.class, "tag91", false, "TAG91");
        public final static Property Fingerprint = new Property(87, String.class, "fingerprint", false, "FINGERPRINT");
    }


    public TransDataDao(DaoConfig config) {
        super(config);
    }
    
    public TransDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANS_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ORDER_NO\" TEXT," + // 1: orderNo
                "\"ORDER_NODIS\" TEXT," + // 2: orderNodis
                "\"AMOUNT\" TEXT," + // 3: amount
                "\"CARD_AMOUNT\" TEXT," + // 4: cardAmount
                "\"CASH_AMOUNT\" TEXT," + // 5: cashAmount
                "\"TIP_AMOUNT\" TEXT," + // 6: tipAmount
                "\"BALANCE\" TEXT," + // 7: balance
                "\"BALANCE_FLAG\" TEXT," + // 8: balanceFlag
                "\"EMV_RESULT\" INTEGER NOT NULL ," + // 9: emvResult
                "\"INTER_ORG_CODE\" TEXT," + // 10: interOrgCode
                "\"TRANS_NO\" INTEGER NOT NULL UNIQUE ," + // 11: transNo
                "\"ORIG_TRANS_NO\" INTEGER NOT NULL ," + // 12: origTransNo
                "\"BATCH_NO\" INTEGER NOT NULL ," + // 13: batchNo
                "\"ORIG_BATCH_NO\" INTEGER NOT NULL ," + // 14: origBatchNo
                "\"TRANS_TYPE\" TEXT," + // 15: transType
                "\"ORIG_TRANS_TYPE\" TEXT," + // 16: origTransType
                "\"MERCH_ID\" TEXT," + // 17: merchID
                "\"MCC\" TEXT," + // 18: mcc
                "\"IS_UPLOAD\" INTEGER NOT NULL ," + // 19: isUpload
                "\"TRANS_STATE\" TEXT," + // 20: transState
                "\"OPER\" TEXT," + // 21: oper
                "\"TRACK1\" TEXT," + // 22: track1
                "\"TRACK2\" TEXT," + // 23: track2
                "\"TRACK3\" TEXT," + // 24: track3
                "\"IS_ENC_TRACK\" INTEGER NOT NULL ," + // 25: isEncTrack
                "\"REASON\" TEXT," + // 26: reason
                "\"RESERVED\" TEXT," + // 27: reserved
                "\"DATETIME\" TEXT," + // 28: datetime
                "\"UN_NUM\" TEXT," + // 29: UnNum
                "\"TIME\" TEXT," + // 30: time
                "\"DATE\" TEXT," + // 31: date
                "\"TERM_ID\" TEXT," + // 32: termID
                "\"PAN\" TEXT," + // 33: pan
                "\"EXP_DATE\" TEXT," + // 34: expDate
                "\"CARD_SERIAL_NO\" TEXT," + // 35: cardSerialNo
                "\"ENTER_MODE\" INTEGER NOT NULL ," + // 36: enterMode
                "\"HAS_PIN\" INTEGER NOT NULL ," + // 37: hasPin
                "\"SEND_ICC_DATA\" TEXT," + // 38: sendIccData
                "\"SCRIPT_TAG\" TEXT," + // 39: scriptTag
                "\"DUP_ICC_DATA\" TEXT," + // 40: dupIccData
                "\"IS_ONLINE_TRANS\" INTEGER NOT NULL ," + // 41: isOnlineTrans
                "\"ORIG_DATE\" TEXT," + // 42: origDate
                "\"ORIG_TIME\" TEXT," + // 43: origTime
                "\"ISSER_CODE\" TEXT," + // 44: isserCode
                "\"ACQ_CODE\" TEXT," + // 45: acqCode
                "\"IS_SUPPORT_BYPASS\" INTEGER NOT NULL ," + // 46: isSupportBypass
                "\"ISSUER_RESP\" TEXT," + // 47: issuerResp
                "\"CENTER_RESP\" TEXT," + // 48: centerResp
                "\"RECV_BANK_RESP\" TEXT," + // 49: recvBankResp
                "\"ICPOSITIVE_DATA\" TEXT," + // 50: ICPositiveData
                "\"RESPONSE_CODE\" TEXT," + // 51: responseCode
                "\"RESPONSE_MSG\" TEXT," + // 52: responseMsg
                "\"SETTLE_DATE\" TEXT," + // 53: settleDate
                "\"ACQ_CENTER_CODE\" TEXT," + // 54: acqCenterCode
                "\"REF_NO\" TEXT," + // 55: refNo
                "\"ORIG_REF_NO\" TEXT," + // 56: origRefNo
                "\"AUTH_CODE\" TEXT," + // 57: authCode
                "\"ORIG_AUTH_CODE\" TEXT," + // 58: origAuthCode
                "\"TC\" TEXT," + // 59: tc
                "\"ARQC\" TEXT," + // 60: arqc
                "\"ARPC\" TEXT," + // 61: arpc
                "\"TVR\" TEXT," + // 62: tvr
                "\"AID\" TEXT," + // 63: aid
                "\"EMV_APP_LABEL\" TEXT," + // 64: emvAppLabel
                "\"EMV_APP_NAME\" TEXT," + // 65: emvAppName
                "\"TSI\" TEXT," + // 66: tsi
                "\"ATC\" TEXT," + // 67: atc
                "\"ORIG_PROC_CODE\" TEXT," + // 68: origProcCode
                "\"QR_CODE\" TEXT," + // 69: qrCode
                "\"ORIG_QR_CODE\" TEXT," + // 70: origQrCode
                "\"QR_VOUCHER\" TEXT," + // 71: qrVoucher
                "\"ORIG_QR_VOUCHER\" TEXT," + // 72: origQrVoucher
                "\"PIN_KSN\" TEXT," + // 73: pinKsn
                "\"DATA_KSN\" TEXT," + // 74: dataKsn
                "\"FIELD52\" TEXT," + // 75: field52
                "\"FIELD58\" TEXT," + // 76: field58
                "\"FIELD22\" TEXT," + // 77: field22
                "\"PROC_CODE\" TEXT," + // 78: procCode
                "\"CARD_HOLDER_NAME\" TEXT," + // 79: cardHolderName
                "\"ELEC_SIGNATURE\" TEXT," + // 80: ElecSignature
                "\"KERNEL_TYPE\" INTEGER NOT NULL ," + // 81: kernelType
                "\"NEED_SCRIPT\" INTEGER NOT NULL ," + // 82: needScript
                "\"TAG71\" TEXT," + // 83: tag71
                "\"TAG72\" TEXT," + // 84: tag72
                "\"TAG8_A\" TEXT," + // 85: tag8A
                "\"TAG91\" TEXT," + // 86: tag91
                "\"FINGERPRINT\" TEXT);"); // 87: fingerprint
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANS_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TransData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(2, orderNo);
        }
 
        String orderNodis = entity.getOrderNodis();
        if (orderNodis != null) {
            stmt.bindString(3, orderNodis);
        }
 
        String amount = entity.getAmount();
        if (amount != null) {
            stmt.bindString(4, amount);
        }
 
        String cardAmount = entity.getCardAmount();
        if (cardAmount != null) {
            stmt.bindString(5, cardAmount);
        }
 
        String cashAmount = entity.getCashAmount();
        if (cashAmount != null) {
            stmt.bindString(6, cashAmount);
        }
 
        String tipAmount = entity.getTipAmount();
        if (tipAmount != null) {
            stmt.bindString(7, tipAmount);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(8, balance);
        }
 
        String balanceFlag = entity.getBalanceFlag();
        if (balanceFlag != null) {
            stmt.bindString(9, balanceFlag);
        }
        stmt.bindLong(10, entity.getEmvResult());
 
        String interOrgCode = entity.getInterOrgCode();
        if (interOrgCode != null) {
            stmt.bindString(11, interOrgCode);
        }
        stmt.bindLong(12, entity.getTransNo());
        stmt.bindLong(13, entity.getOrigTransNo());
        stmt.bindLong(14, entity.getBatchNo());
        stmt.bindLong(15, entity.getOrigBatchNo());
 
        String transType = entity.getTransType();
        if (transType != null) {
            stmt.bindString(16, transType);
        }
 
        String origTransType = entity.getOrigTransType();
        if (origTransType != null) {
            stmt.bindString(17, origTransType);
        }
 
        String merchID = entity.getMerchID();
        if (merchID != null) {
            stmt.bindString(18, merchID);
        }
 
        String mcc = entity.getMcc();
        if (mcc != null) {
            stmt.bindString(19, mcc);
        }
        stmt.bindLong(20, entity.getIsUpload() ? 1L: 0L);
 
        String transState = entity.getTransState();
        if (transState != null) {
            stmt.bindString(21, transState);
        }
 
        String oper = entity.getOper();
        if (oper != null) {
            stmt.bindString(22, oper);
        }
 
        String track1 = entity.getTrack1();
        if (track1 != null) {
            stmt.bindString(23, track1);
        }
 
        String track2 = entity.getTrack2();
        if (track2 != null) {
            stmt.bindString(24, track2);
        }
 
        String track3 = entity.getTrack3();
        if (track3 != null) {
            stmt.bindString(25, track3);
        }
        stmt.bindLong(26, entity.getIsEncTrack() ? 1L: 0L);
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(27, reason);
        }
 
        String reserved = entity.getReserved();
        if (reserved != null) {
            stmt.bindString(28, reserved);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(29, datetime);
        }
 
        String UnNum = entity.getUnNum();
        if (UnNum != null) {
            stmt.bindString(30, UnNum);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(31, time);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(32, date);
        }
 
        String termID = entity.getTermID();
        if (termID != null) {
            stmt.bindString(33, termID);
        }
 
        String pan = entity.getPan();
        if (pan != null) {
            stmt.bindString(34, pan);
        }
 
        String expDate = entity.getExpDate();
        if (expDate != null) {
            stmt.bindString(35, expDate);
        }
 
        String cardSerialNo = entity.getCardSerialNo();
        if (cardSerialNo != null) {
            stmt.bindString(36, cardSerialNo);
        }
        stmt.bindLong(37, entity.getEnterMode());
        stmt.bindLong(38, entity.getHasPin() ? 1L: 0L);
 
        String sendIccData = entity.getSendIccData();
        if (sendIccData != null) {
            stmt.bindString(39, sendIccData);
        }
 
        String scriptTag = entity.getScriptTag();
        if (scriptTag != null) {
            stmt.bindString(40, scriptTag);
        }
 
        String dupIccData = entity.getDupIccData();
        if (dupIccData != null) {
            stmt.bindString(41, dupIccData);
        }
        stmt.bindLong(42, entity.getIsOnlineTrans() ? 1L: 0L);
 
        String origDate = entity.getOrigDate();
        if (origDate != null) {
            stmt.bindString(43, origDate);
        }
 
        String origTime = entity.getOrigTime();
        if (origTime != null) {
            stmt.bindString(44, origTime);
        }
 
        String isserCode = entity.getIsserCode();
        if (isserCode != null) {
            stmt.bindString(45, isserCode);
        }
 
        String acqCode = entity.getAcqCode();
        if (acqCode != null) {
            stmt.bindString(46, acqCode);
        }
        stmt.bindLong(47, entity.getIsSupportBypass() ? 1L: 0L);
 
        String issuerResp = entity.getIssuerResp();
        if (issuerResp != null) {
            stmt.bindString(48, issuerResp);
        }
 
        String centerResp = entity.getCenterResp();
        if (centerResp != null) {
            stmt.bindString(49, centerResp);
        }
 
        String recvBankResp = entity.getRecvBankResp();
        if (recvBankResp != null) {
            stmt.bindString(50, recvBankResp);
        }
 
        String ICPositiveData = entity.getICPositiveData();
        if (ICPositiveData != null) {
            stmt.bindString(51, ICPositiveData);
        }
 
        String responseCode = entity.getResponseCode();
        if (responseCode != null) {
            stmt.bindString(52, responseCode);
        }
 
        String responseMsg = entity.getResponseMsg();
        if (responseMsg != null) {
            stmt.bindString(53, responseMsg);
        }
 
        String settleDate = entity.getSettleDate();
        if (settleDate != null) {
            stmt.bindString(54, settleDate);
        }
 
        String acqCenterCode = entity.getAcqCenterCode();
        if (acqCenterCode != null) {
            stmt.bindString(55, acqCenterCode);
        }
 
        String refNo = entity.getRefNo();
        if (refNo != null) {
            stmt.bindString(56, refNo);
        }
 
        String origRefNo = entity.getOrigRefNo();
        if (origRefNo != null) {
            stmt.bindString(57, origRefNo);
        }
 
        String authCode = entity.getAuthCode();
        if (authCode != null) {
            stmt.bindString(58, authCode);
        }
 
        String origAuthCode = entity.getOrigAuthCode();
        if (origAuthCode != null) {
            stmt.bindString(59, origAuthCode);
        }
 
        String tc = entity.getTc();
        if (tc != null) {
            stmt.bindString(60, tc);
        }
 
        String arqc = entity.getArqc();
        if (arqc != null) {
            stmt.bindString(61, arqc);
        }
 
        String arpc = entity.getArpc();
        if (arpc != null) {
            stmt.bindString(62, arpc);
        }
 
        String tvr = entity.getTvr();
        if (tvr != null) {
            stmt.bindString(63, tvr);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(64, aid);
        }
 
        String emvAppLabel = entity.getEmvAppLabel();
        if (emvAppLabel != null) {
            stmt.bindString(65, emvAppLabel);
        }
 
        String emvAppName = entity.getEmvAppName();
        if (emvAppName != null) {
            stmt.bindString(66, emvAppName);
        }
 
        String tsi = entity.getTsi();
        if (tsi != null) {
            stmt.bindString(67, tsi);
        }
 
        String atc = entity.getAtc();
        if (atc != null) {
            stmt.bindString(68, atc);
        }
 
        String origProcCode = entity.getOrigProcCode();
        if (origProcCode != null) {
            stmt.bindString(69, origProcCode);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(70, qrCode);
        }
 
        String origQrCode = entity.getOrigQrCode();
        if (origQrCode != null) {
            stmt.bindString(71, origQrCode);
        }
 
        String qrVoucher = entity.getQrVoucher();
        if (qrVoucher != null) {
            stmt.bindString(72, qrVoucher);
        }
 
        String origQrVoucher = entity.getOrigQrVoucher();
        if (origQrVoucher != null) {
            stmt.bindString(73, origQrVoucher);
        }
 
        String pinKsn = entity.getPinKsn();
        if (pinKsn != null) {
            stmt.bindString(74, pinKsn);
        }
 
        String dataKsn = entity.getDataKsn();
        if (dataKsn != null) {
            stmt.bindString(75, dataKsn);
        }
 
        String field52 = entity.getField52();
        if (field52 != null) {
            stmt.bindString(76, field52);
        }
 
        String field58 = entity.getField58();
        if (field58 != null) {
            stmt.bindString(77, field58);
        }
 
        String field22 = entity.getField22();
        if (field22 != null) {
            stmt.bindString(78, field22);
        }
 
        String procCode = entity.getProcCode();
        if (procCode != null) {
            stmt.bindString(79, procCode);
        }
 
        String cardHolderName = entity.getCardHolderName();
        if (cardHolderName != null) {
            stmt.bindString(80, cardHolderName);
        }
 
        String ElecSignature = entity.getElecSignature();
        if (ElecSignature != null) {
            stmt.bindString(81, ElecSignature);
        }
        stmt.bindLong(82, entity.getKernelType());
        stmt.bindLong(83, entity.getNeedScript() ? 1L: 0L);
 
        String tag71 = entity.getTag71();
        if (tag71 != null) {
            stmt.bindString(84, tag71);
        }
 
        String tag72 = entity.getTag72();
        if (tag72 != null) {
            stmt.bindString(85, tag72);
        }
 
        String tag8A = entity.getTag8A();
        if (tag8A != null) {
            stmt.bindString(86, tag8A);
        }
 
        String tag91 = entity.getTag91();
        if (tag91 != null) {
            stmt.bindString(87, tag91);
        }
 
        String fingerprint = entity.getFingerprint();
        if (fingerprint != null) {
            stmt.bindString(88, fingerprint);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TransData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(2, orderNo);
        }
 
        String orderNodis = entity.getOrderNodis();
        if (orderNodis != null) {
            stmt.bindString(3, orderNodis);
        }
 
        String amount = entity.getAmount();
        if (amount != null) {
            stmt.bindString(4, amount);
        }
 
        String cardAmount = entity.getCardAmount();
        if (cardAmount != null) {
            stmt.bindString(5, cardAmount);
        }
 
        String cashAmount = entity.getCashAmount();
        if (cashAmount != null) {
            stmt.bindString(6, cashAmount);
        }
 
        String tipAmount = entity.getTipAmount();
        if (tipAmount != null) {
            stmt.bindString(7, tipAmount);
        }
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(8, balance);
        }
 
        String balanceFlag = entity.getBalanceFlag();
        if (balanceFlag != null) {
            stmt.bindString(9, balanceFlag);
        }
        stmt.bindLong(10, entity.getEmvResult());
 
        String interOrgCode = entity.getInterOrgCode();
        if (interOrgCode != null) {
            stmt.bindString(11, interOrgCode);
        }
        stmt.bindLong(12, entity.getTransNo());
        stmt.bindLong(13, entity.getOrigTransNo());
        stmt.bindLong(14, entity.getBatchNo());
        stmt.bindLong(15, entity.getOrigBatchNo());
 
        String transType = entity.getTransType();
        if (transType != null) {
            stmt.bindString(16, transType);
        }
 
        String origTransType = entity.getOrigTransType();
        if (origTransType != null) {
            stmt.bindString(17, origTransType);
        }
 
        String merchID = entity.getMerchID();
        if (merchID != null) {
            stmt.bindString(18, merchID);
        }
 
        String mcc = entity.getMcc();
        if (mcc != null) {
            stmt.bindString(19, mcc);
        }
        stmt.bindLong(20, entity.getIsUpload() ? 1L: 0L);
 
        String transState = entity.getTransState();
        if (transState != null) {
            stmt.bindString(21, transState);
        }
 
        String oper = entity.getOper();
        if (oper != null) {
            stmt.bindString(22, oper);
        }
 
        String track1 = entity.getTrack1();
        if (track1 != null) {
            stmt.bindString(23, track1);
        }
 
        String track2 = entity.getTrack2();
        if (track2 != null) {
            stmt.bindString(24, track2);
        }
 
        String track3 = entity.getTrack3();
        if (track3 != null) {
            stmt.bindString(25, track3);
        }
        stmt.bindLong(26, entity.getIsEncTrack() ? 1L: 0L);
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(27, reason);
        }
 
        String reserved = entity.getReserved();
        if (reserved != null) {
            stmt.bindString(28, reserved);
        }
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(29, datetime);
        }
 
        String UnNum = entity.getUnNum();
        if (UnNum != null) {
            stmt.bindString(30, UnNum);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(31, time);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(32, date);
        }
 
        String termID = entity.getTermID();
        if (termID != null) {
            stmt.bindString(33, termID);
        }
 
        String pan = entity.getPan();
        if (pan != null) {
            stmt.bindString(34, pan);
        }
 
        String expDate = entity.getExpDate();
        if (expDate != null) {
            stmt.bindString(35, expDate);
        }
 
        String cardSerialNo = entity.getCardSerialNo();
        if (cardSerialNo != null) {
            stmt.bindString(36, cardSerialNo);
        }
        stmt.bindLong(37, entity.getEnterMode());
        stmt.bindLong(38, entity.getHasPin() ? 1L: 0L);
 
        String sendIccData = entity.getSendIccData();
        if (sendIccData != null) {
            stmt.bindString(39, sendIccData);
        }
 
        String scriptTag = entity.getScriptTag();
        if (scriptTag != null) {
            stmt.bindString(40, scriptTag);
        }
 
        String dupIccData = entity.getDupIccData();
        if (dupIccData != null) {
            stmt.bindString(41, dupIccData);
        }
        stmt.bindLong(42, entity.getIsOnlineTrans() ? 1L: 0L);
 
        String origDate = entity.getOrigDate();
        if (origDate != null) {
            stmt.bindString(43, origDate);
        }
 
        String origTime = entity.getOrigTime();
        if (origTime != null) {
            stmt.bindString(44, origTime);
        }
 
        String isserCode = entity.getIsserCode();
        if (isserCode != null) {
            stmt.bindString(45, isserCode);
        }
 
        String acqCode = entity.getAcqCode();
        if (acqCode != null) {
            stmt.bindString(46, acqCode);
        }
        stmt.bindLong(47, entity.getIsSupportBypass() ? 1L: 0L);
 
        String issuerResp = entity.getIssuerResp();
        if (issuerResp != null) {
            stmt.bindString(48, issuerResp);
        }
 
        String centerResp = entity.getCenterResp();
        if (centerResp != null) {
            stmt.bindString(49, centerResp);
        }
 
        String recvBankResp = entity.getRecvBankResp();
        if (recvBankResp != null) {
            stmt.bindString(50, recvBankResp);
        }
 
        String ICPositiveData = entity.getICPositiveData();
        if (ICPositiveData != null) {
            stmt.bindString(51, ICPositiveData);
        }
 
        String responseCode = entity.getResponseCode();
        if (responseCode != null) {
            stmt.bindString(52, responseCode);
        }
 
        String responseMsg = entity.getResponseMsg();
        if (responseMsg != null) {
            stmt.bindString(53, responseMsg);
        }
 
        String settleDate = entity.getSettleDate();
        if (settleDate != null) {
            stmt.bindString(54, settleDate);
        }
 
        String acqCenterCode = entity.getAcqCenterCode();
        if (acqCenterCode != null) {
            stmt.bindString(55, acqCenterCode);
        }
 
        String refNo = entity.getRefNo();
        if (refNo != null) {
            stmt.bindString(56, refNo);
        }
 
        String origRefNo = entity.getOrigRefNo();
        if (origRefNo != null) {
            stmt.bindString(57, origRefNo);
        }
 
        String authCode = entity.getAuthCode();
        if (authCode != null) {
            stmt.bindString(58, authCode);
        }
 
        String origAuthCode = entity.getOrigAuthCode();
        if (origAuthCode != null) {
            stmt.bindString(59, origAuthCode);
        }
 
        String tc = entity.getTc();
        if (tc != null) {
            stmt.bindString(60, tc);
        }
 
        String arqc = entity.getArqc();
        if (arqc != null) {
            stmt.bindString(61, arqc);
        }
 
        String arpc = entity.getArpc();
        if (arpc != null) {
            stmt.bindString(62, arpc);
        }
 
        String tvr = entity.getTvr();
        if (tvr != null) {
            stmt.bindString(63, tvr);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(64, aid);
        }
 
        String emvAppLabel = entity.getEmvAppLabel();
        if (emvAppLabel != null) {
            stmt.bindString(65, emvAppLabel);
        }
 
        String emvAppName = entity.getEmvAppName();
        if (emvAppName != null) {
            stmt.bindString(66, emvAppName);
        }
 
        String tsi = entity.getTsi();
        if (tsi != null) {
            stmt.bindString(67, tsi);
        }
 
        String atc = entity.getAtc();
        if (atc != null) {
            stmt.bindString(68, atc);
        }
 
        String origProcCode = entity.getOrigProcCode();
        if (origProcCode != null) {
            stmt.bindString(69, origProcCode);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(70, qrCode);
        }
 
        String origQrCode = entity.getOrigQrCode();
        if (origQrCode != null) {
            stmt.bindString(71, origQrCode);
        }
 
        String qrVoucher = entity.getQrVoucher();
        if (qrVoucher != null) {
            stmt.bindString(72, qrVoucher);
        }
 
        String origQrVoucher = entity.getOrigQrVoucher();
        if (origQrVoucher != null) {
            stmt.bindString(73, origQrVoucher);
        }
 
        String pinKsn = entity.getPinKsn();
        if (pinKsn != null) {
            stmt.bindString(74, pinKsn);
        }
 
        String dataKsn = entity.getDataKsn();
        if (dataKsn != null) {
            stmt.bindString(75, dataKsn);
        }
 
        String field52 = entity.getField52();
        if (field52 != null) {
            stmt.bindString(76, field52);
        }
 
        String field58 = entity.getField58();
        if (field58 != null) {
            stmt.bindString(77, field58);
        }
 
        String field22 = entity.getField22();
        if (field22 != null) {
            stmt.bindString(78, field22);
        }
 
        String procCode = entity.getProcCode();
        if (procCode != null) {
            stmt.bindString(79, procCode);
        }
 
        String cardHolderName = entity.getCardHolderName();
        if (cardHolderName != null) {
            stmt.bindString(80, cardHolderName);
        }
 
        String ElecSignature = entity.getElecSignature();
        if (ElecSignature != null) {
            stmt.bindString(81, ElecSignature);
        }
        stmt.bindLong(82, entity.getKernelType());
        stmt.bindLong(83, entity.getNeedScript() ? 1L: 0L);
 
        String tag71 = entity.getTag71();
        if (tag71 != null) {
            stmt.bindString(84, tag71);
        }
 
        String tag72 = entity.getTag72();
        if (tag72 != null) {
            stmt.bindString(85, tag72);
        }
 
        String tag8A = entity.getTag8A();
        if (tag8A != null) {
            stmt.bindString(86, tag8A);
        }
 
        String tag91 = entity.getTag91();
        if (tag91 != null) {
            stmt.bindString(87, tag91);
        }
 
        String fingerprint = entity.getFingerprint();
        if (fingerprint != null) {
            stmt.bindString(88, fingerprint);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TransData readEntity(Cursor cursor, int offset) {
        TransData entity = new TransData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // orderNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // orderNodis
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // amount
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // cardAmount
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cashAmount
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tipAmount
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // balance
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // balanceFlag
            (byte) cursor.getShort(offset + 9), // emvResult
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // interOrgCode
            cursor.getLong(offset + 11), // transNo
            cursor.getLong(offset + 12), // origTransNo
            cursor.getLong(offset + 13), // batchNo
            cursor.getLong(offset + 14), // origBatchNo
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // transType
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // origTransType
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // merchID
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // mcc
            cursor.getShort(offset + 19) != 0, // isUpload
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // transState
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // oper
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // track1
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // track2
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // track3
            cursor.getShort(offset + 25) != 0, // isEncTrack
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // reason
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // reserved
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // datetime
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // UnNum
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // time
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // date
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // termID
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // pan
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // expDate
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // cardSerialNo
            cursor.getInt(offset + 36), // enterMode
            cursor.getShort(offset + 37) != 0, // hasPin
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // sendIccData
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // scriptTag
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // dupIccData
            cursor.getShort(offset + 41) != 0, // isOnlineTrans
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // origDate
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // origTime
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // isserCode
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // acqCode
            cursor.getShort(offset + 46) != 0, // isSupportBypass
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // issuerResp
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // centerResp
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // recvBankResp
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // ICPositiveData
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // responseCode
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // responseMsg
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // settleDate
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // acqCenterCode
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // refNo
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // origRefNo
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // authCode
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // origAuthCode
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // tc
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // arqc
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // arpc
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // tvr
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // aid
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // emvAppLabel
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // emvAppName
            cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66), // tsi
            cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67), // atc
            cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68), // origProcCode
            cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69), // qrCode
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70), // origQrCode
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71), // qrVoucher
            cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72), // origQrVoucher
            cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73), // pinKsn
            cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74), // dataKsn
            cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75), // field52
            cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76), // field58
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77), // field22
            cursor.isNull(offset + 78) ? null : cursor.getString(offset + 78), // procCode
            cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79), // cardHolderName
            cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80), // ElecSignature
            cursor.getInt(offset + 81), // kernelType
            cursor.getShort(offset + 82) != 0, // needScript
            cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83), // tag71
            cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84), // tag72
            cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85), // tag8A
            cursor.isNull(offset + 86) ? null : cursor.getString(offset + 86), // tag91
            cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87) // fingerprint
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TransData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOrderNodis(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAmount(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCardAmount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCashAmount(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTipAmount(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBalance(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBalanceFlag(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEmvResult((byte) cursor.getShort(offset + 9));
        entity.setInterOrgCode(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTransNo(cursor.getLong(offset + 11));
        entity.setOrigTransNo(cursor.getLong(offset + 12));
        entity.setBatchNo(cursor.getLong(offset + 13));
        entity.setOrigBatchNo(cursor.getLong(offset + 14));
        entity.setTransType(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setOrigTransType(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setMerchID(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setMcc(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setIsUpload(cursor.getShort(offset + 19) != 0);
        entity.setTransState(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setOper(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setTrack1(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTrack2(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setTrack3(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setIsEncTrack(cursor.getShort(offset + 25) != 0);
        entity.setReason(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setReserved(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setDatetime(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setUnNum(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setTime(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setDate(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTermID(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setPan(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setExpDate(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setCardSerialNo(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setEnterMode(cursor.getInt(offset + 36));
        entity.setHasPin(cursor.getShort(offset + 37) != 0);
        entity.setSendIccData(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setScriptTag(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setDupIccData(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setIsOnlineTrans(cursor.getShort(offset + 41) != 0);
        entity.setOrigDate(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setOrigTime(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setIsserCode(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setAcqCode(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setIsSupportBypass(cursor.getShort(offset + 46) != 0);
        entity.setIssuerResp(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setCenterResp(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setRecvBankResp(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setICPositiveData(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setResponseCode(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setResponseMsg(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setSettleDate(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setAcqCenterCode(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setRefNo(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setOrigRefNo(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setAuthCode(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setOrigAuthCode(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setTc(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setArqc(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setArpc(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setTvr(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setAid(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setEmvAppLabel(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setEmvAppName(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setTsi(cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66));
        entity.setAtc(cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67));
        entity.setOrigProcCode(cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68));
        entity.setQrCode(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setOrigQrCode(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setQrVoucher(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
        entity.setOrigQrVoucher(cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72));
        entity.setPinKsn(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setDataKsn(cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74));
        entity.setField52(cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75));
        entity.setField58(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setField22(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setProcCode(cursor.isNull(offset + 78) ? null : cursor.getString(offset + 78));
        entity.setCardHolderName(cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79));
        entity.setElecSignature(cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80));
        entity.setKernelType(cursor.getInt(offset + 81));
        entity.setNeedScript(cursor.getShort(offset + 82) != 0);
        entity.setTag71(cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83));
        entity.setTag72(cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84));
        entity.setTag8A(cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85));
        entity.setTag91(cursor.isNull(offset + 86) ? null : cursor.getString(offset + 86));
        entity.setFingerprint(cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TransData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TransData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TransData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
