package com.topwise.premierpay.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.topwise.premierpay.trans.model.TransStatusSum;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANS_STATUS_SUM".
*/
public class TransStatusSumDao extends AbstractDao<TransStatusSum, Long> {

    public static final String TABLENAME = "TRANS_STATUS_SUM";

    /**
     * Properties of entity TransStatusSum.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CommType = new Property(1, int.class, "commType", false, "COMM_TYPE");
        public final static Property ConnectTime = new Property(2, long.class, "connectTime", false, "CONNECT_TIME");
        public final static Property SendTime = new Property(3, long.class, "sendTime", false, "SEND_TIME");
        public final static Property ReceiveTime = new Property(4, long.class, "receiveTime", false, "RECEIVE_TIME");
        public final static Property PackTime = new Property(5, long.class, "packTime", false, "PACK_TIME");
        public final static Property UnpackTime = new Property(6, long.class, "unpackTime", false, "UNPACK_TIME");
        public final static Property CommTime = new Property(7, long.class, "commTime", false, "COMM_TIME");
        public final static Property SingleValue = new Property(8, String.class, "singleValue", false, "SINGLE_VALUE");
        public final static Property Result = new Property(9, int.class, "result", false, "RESULT");
        public final static Property Datetime = new Property(10, String.class, "datetime", false, "DATETIME");
        public final static Property ConnCount = new Property(11, int.class, "connCount", false, "CONN_COUNT");
    }


    public TransStatusSumDao(DaoConfig config) {
        super(config);
    }
    
    public TransStatusSumDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANS_STATUS_SUM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COMM_TYPE\" INTEGER NOT NULL ," + // 1: commType
                "\"CONNECT_TIME\" INTEGER NOT NULL ," + // 2: connectTime
                "\"SEND_TIME\" INTEGER NOT NULL ," + // 3: sendTime
                "\"RECEIVE_TIME\" INTEGER NOT NULL ," + // 4: receiveTime
                "\"PACK_TIME\" INTEGER NOT NULL ," + // 5: packTime
                "\"UNPACK_TIME\" INTEGER NOT NULL ," + // 6: unpackTime
                "\"COMM_TIME\" INTEGER NOT NULL ," + // 7: commTime
                "\"SINGLE_VALUE\" TEXT," + // 8: singleValue
                "\"RESULT\" INTEGER NOT NULL ," + // 9: result
                "\"DATETIME\" TEXT," + // 10: datetime
                "\"CONN_COUNT\" INTEGER NOT NULL );"); // 11: connCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANS_STATUS_SUM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TransStatusSum entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCommType());
        stmt.bindLong(3, entity.getConnectTime());
        stmt.bindLong(4, entity.getSendTime());
        stmt.bindLong(5, entity.getReceiveTime());
        stmt.bindLong(6, entity.getPackTime());
        stmt.bindLong(7, entity.getUnpackTime());
        stmt.bindLong(8, entity.getCommTime());
 
        String singleValue = entity.getSingleValue();
        if (singleValue != null) {
            stmt.bindString(9, singleValue);
        }
        stmt.bindLong(10, entity.getResult());
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(11, datetime);
        }
        stmt.bindLong(12, entity.getConnCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TransStatusSum entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCommType());
        stmt.bindLong(3, entity.getConnectTime());
        stmt.bindLong(4, entity.getSendTime());
        stmt.bindLong(5, entity.getReceiveTime());
        stmt.bindLong(6, entity.getPackTime());
        stmt.bindLong(7, entity.getUnpackTime());
        stmt.bindLong(8, entity.getCommTime());
 
        String singleValue = entity.getSingleValue();
        if (singleValue != null) {
            stmt.bindString(9, singleValue);
        }
        stmt.bindLong(10, entity.getResult());
 
        String datetime = entity.getDatetime();
        if (datetime != null) {
            stmt.bindString(11, datetime);
        }
        stmt.bindLong(12, entity.getConnCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TransStatusSum readEntity(Cursor cursor, int offset) {
        TransStatusSum entity = new TransStatusSum( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // commType
            cursor.getLong(offset + 2), // connectTime
            cursor.getLong(offset + 3), // sendTime
            cursor.getLong(offset + 4), // receiveTime
            cursor.getLong(offset + 5), // packTime
            cursor.getLong(offset + 6), // unpackTime
            cursor.getLong(offset + 7), // commTime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // singleValue
            cursor.getInt(offset + 9), // result
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // datetime
            cursor.getInt(offset + 11) // connCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TransStatusSum entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCommType(cursor.getInt(offset + 1));
        entity.setConnectTime(cursor.getLong(offset + 2));
        entity.setSendTime(cursor.getLong(offset + 3));
        entity.setReceiveTime(cursor.getLong(offset + 4));
        entity.setPackTime(cursor.getLong(offset + 5));
        entity.setUnpackTime(cursor.getLong(offset + 6));
        entity.setCommTime(cursor.getLong(offset + 7));
        entity.setSingleValue(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setResult(cursor.getInt(offset + 9));
        entity.setDatetime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setConnCount(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TransStatusSum entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TransStatusSum entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TransStatusSum entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
